### ISSUE TITLE
update it 

### ISSUE THREAD

**Issue by satyammpandeyy** [thatsmyface/PokeDisco#1]
update it please with adding trading commands, makeing a function like <prefix>redirectspawn #channel

**Comment by MntRushmore** [comment]
@sp-sketch How Did U Host It Urselv?

**Comment by satyammpandeyy** [comment]
nvm i made my own poke bot (inspired by poke disco) its same as poke-cord :)

**Comment by MntRushmore** [comment]
Can I Have The Github Link? @sp-sketch 
And @thatsmyface Pls Tell Me If We Can Host Ourselves!

**Comment by satyammpandeyy** [comment]
no my projects are not open source

**Comment by MntRushmore** [comment]
Wait U Made This? @sp-sketch Cause it Shows @thatsmyface As The Owner?
If U Made Can I Have The Invite Of Bot? I Wann Use It!

**Comment by satyammpandeyy** [comment]
No I did not made pokedisco I made my own like PokeCord

**Comment by satyammpandeyy** [comment]
https://discord.gg/pokesoul
